[DependencyScanning] Fix warnings
This patch fixes:

  clang/lib/Tooling/DependencyScanning/DependencyScannerImpl.cpp:733:10:
  error: unused variable 'ArgSize' [-Werror,-Wunused-variable]

  clang/lib/Tooling/DependencyScanning/DependencyScannerImpl.cpp:735:15:
  error: unused variable 'FirstArg' [-Werror,-Wunused-variable]

(cherry picked from commit 8552a8fbffd0573331ce2790784d090349fd885b)