[lldb][test] Disable test_step_over_starting_inside_coroutine on Aarch64 linux
This fails with the error:

```
  File "/home/build-user/llvm-project/lldb/test/API/lang/swift/yielding_accessors/TestSwiftYieldingAccessors.py", line 65, in test_step_over_starting_inside_coroutine
    self.hit_correct_line(thread, "coroutine call site")
  File "/home/build-user/llvm-project/lldb/test/API/lang/swift/yielding_accessors/TestSwiftYieldingAccessors.py", line 31, in hit_correct_line
    self.assertTrue(
AssertionError: False is not true : Stepped to line 11 instead of expected 18 with pattern 'coroutine call site'
Backtrace =
frame #0: 0x0000aaaac1b76d04 a.out`S.COMPUTED_PROPERTY.yielding_mutate() at main.swift:11:7
frame #1: 0x0000ffffbba884c4 libc.so.6`___lldb_unnamed_symbol_28450 + 116.
```